# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Find dotfiles base path, with the -f option for full path if necessary
if readlink -f ~/.bashrc > /dev/null 2>&1; then
	DOTFILES=$(dirname "$(dirname $(readlink -f ~/.bashrc))")
else
	DOTFILES=$(dirname "$(dirname $(readlink ~/.bashrc))")
fi

# Make personal utilities available
PATH=$DOTFILES/bin:$PATH
export PATH

# Source the dotfiles (order matters)
# Order:.{function,function_*,path,env,alias,grep,prompt,nvm,completion,custom}
for DOTFILE in "$DOTFILES"/system/.{functions,path,env,alias,local,prompt,prompt_git}; do
  [ -f "$DOTFILE" ] && source "$DOTFILE"
done

if is-macos; then
    for DOTFILE in "$DOTFILES"/system/.{functions,path,env,alias}_macos; do
        [  -f "$DOTFILE" ] && source "$DOTFILE"
    done
fi

# Clean up
unset DOTFILE
#unset DOTFILES
