#!/usr/bin/env bash

CWD=$(pwd)

echo "Checking if git is installed..."
if ! which git > /dev/null; then
    echo "Installing git..."
    sudo apt-get install -y git
fi

echo "Checking if dotfiles are installed..."
if [ -z "$DOTFILES" ]; then
    echo "Installing dotfiles..."
    mkdir -p ~/projects
    cd ~/projects
    git clone --depth 1 https://github.com/bertvanpoecke/dotfiles.git
    cd dotfiles
    yes | ./install
else
    echo "All done."
fi

cd "$CWD"