#!/usr/bin/env bash

read -p "Do you want to install the dotfiles? Remark this will overwrite exisiting dotfiles! [y|n] " -r
if [[ ! $REPLY =~ ^[Yy]$ ]]; then exit; fi

echo "Linking profile files and directories..."
dotfiles="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Files e.g.: runcom/bash_profile runcom/bashrc vim vim/gvimrc vim/vimrc ...
for file in runcom/bash_profile runcom/bashrc; do
    homefile=~/.`echo $file | sed -Ee 's/[a-z]+\///'` #This regular expression removes the folder before the filename. e.g.: vim/vimrc --> vimrc
    if [ -e $homefile ]; then
        cp $homefile ${homefile}_old
    fi
    rm -rf "$homefile" 2>/dev/null
    ln -s "$dotfiles/$file" "$homefile"
done

# echo "Setting up git..."
# $dotfiles/bin/git-setup-prefs

read -p "Do you also want to reset macOS defaults? Remark this will overwrite exisiting settings! [iamsure] " -r
if [[ $REPLY == "iamsure" ]]; then
    echo "Setting up macOS defaults..."
    # source $dotfiles/system/.defaults_macos
else
    echo "macOS defaults are NOT set."
fi

# Clean up
unset file dotfiles

echo "Done."

echo "Run the following to activate:"
echo "  cd && source .bashrc"